blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://react-native-nitro-geolocation.pages.dev
    about: Check the documentation for guides and API reference
  - name: Discussions
    url: https://github.com/jingjing2222/react-native-nitro-geolocation/discussions
    about: Ask questions and discuss ideas with the community
